/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const addItem: string;
declare const hidden: string;
declare const toggle: string;
declare const inputs: string;
declare const binNoInput: string;
declare const nameInput: string;
declare const sizePicker: string;
declare const loadingOverlay: string;
declare const fadeInOver: string;
declare const fadeOutOver: string;
declare const visible: string;

export {
	container,
	addItem,
	hidden,
	toggle,
	inputs,
	binNoInput,
	nameInput,
	sizePicker,
	loadingOverlay,
	visible
};

declare const __default_export__: {
	container: typeof container;
	addItem: typeof addItem;
	hidden: typeof hidden;
	toggle: typeof toggle;
	inputs: typeof inputs;
	binNoInput: typeof binNoInput;
	nameInput: typeof nameInput;
	sizePicker: typeof sizePicker;
	loadingOverlay: typeof loadingOverlay;
	"fade-in-over": typeof fadeInOver;
	"fade-out-over": typeof fadeOutOver;
	visible: typeof visible;
};
export default __default_export__;
