/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const main: string;
declare const mainHeader: string;
declare const search: string;

export {
	main,
	mainHeader,
	search
};

declare const __default_export__: {
	main: typeof main;
	mainHeader: typeof mainHeader;
	search: typeof search;
};
export default __default_export__;
