/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const listContainer: string;
declare const list: string;
declare const lowScore: string;
declare const itemLocation: string;
declare const itemSlash: string;
declare const itemBinNo: string;
declare const itemName: string;

export {
	listContainer,
	list,
	lowScore,
	itemLocation,
	itemSlash,
	itemBinNo,
	itemName
};

declare const __default_export__: {
	listContainer: typeof listContainer;
	list: typeof list;
	lowScore: typeof lowScore;
	itemLocation: typeof itemLocation;
	itemSlash: typeof itemSlash;
	itemBinNo: typeof itemBinNo;
	itemName: typeof itemName;
};
export default __default_export__;
