/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const errorMessage: string;
declare const listContainer: string;
declare const grid: string;
declare const lowScore: string;
declare const itemLocation: string;
declare const itemBinNo: string;
declare const itemSlash: string;
declare const itemName: string;
declare const itemSize: string;

export {
	errorMessage,
	listContainer,
	grid,
	lowScore,
	itemLocation,
	itemBinNo,
	itemSlash,
	itemName,
	itemSize
};

declare const __default_export__: {
	errorMessage: typeof errorMessage;
	listContainer: typeof listContainer;
	grid: typeof grid;
	lowScore: typeof lowScore;
	itemLocation: typeof itemLocation;
	itemBinNo: typeof itemBinNo;
	itemSlash: typeof itemSlash;
	itemName: typeof itemName;
	itemSize: typeof itemSize;
};
export default __default_export__;
